-- Reglas enganche

INSERT INTO REGLAS_MULTIPLICAR VALUES('1','19','','<=','','','1','1');
INSERT INTO REGLAS_MULTIPLICAR VALUES('2','20','35','>=','&&','<=','2','1');
INSERT INTO REGLAS_MULTIPLICAR VALUES('3','36','50','>=','&&','<=','3','1');
INSERT INTO REGLAS_MULTIPLICAR VALUES('4','51','','>','','','4','1');

-- Reglas Plazo

INSERT INTO REGLAS_MULTIPLICAR VALUES('5','72','','==','','','1','2');
INSERT INTO REGLAS_MULTIPLICAR VALUES('6','60','','==','','','2','2');
INSERT INTO REGLAS_MULTIPLICAR VALUES('7','48','','==','','','3','2');
INSERT INTO REGLAS_MULTIPLICAR VALUES('8','36','','<=','','','4','2');

