INSERT INTO REGLAS_MULTIPLICAR VALUES('1','19','','<=','','','1','1');
INSERT INTO REGLAS_MULTIPLICAR VALUES('2','20','35','>=','&&','<=','2','1');
INSERT INTO REGLAS_MULTIPLICAR VALUES('3','36','50','>=','&&','<=','3','1');
INSERT INTO REGLAS_MULTIPLICAR VALUES('4','51','','>','','','4','1');